services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - REDIS_URI_KLAGE_JOB_STATUS=redis://valkey:6379/0
      - REDIS_USERNAME_KLAGE_JOB_STATUS=default
      - REDIS_PASSWORD_KLAGE_JOB_STATUS=redis_password
      - API_KEY_SECRET=secret
  valkey:
    image: valkey/valkey:alpine
    restart: always
    ports:
      - '6379:6379'
    command: valkey-server --loglevel warning --requirepass redis_password
    volumes: 
      - ./valkey-data:/data
